import { Inter } from "next/font/google";
import "@styles/main.scss";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, modal }) {
  return (
    <html lang="fr">
      <body className={inter.className}>
        {children}
        {modal}
        <Footer />
      </body>
    </html>
  );
}
